#!/bin/bash

CNT="[\e[1;36mNOTE\e[0m]"
COK="[\e[1;32mOK\e[0m]"
CER="[\e[1;31mERROR\e[0m]"
CAT="[\e[1;37mATTENTION\e[0m]"
CWR="[\e[1;35mWARNING\e[0m]"
CAC="[\e[1;33mACTION\e[0m]"

echo -e "$CNT - Installing oh-my-zsh and plugins"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

echo -e "$CNT - Installing config/script symlinks and arranging directories"

mkdir ~/.config/xmonad
mkdir ~/.config/rofi
mkdir ~/.config/polybar
mkdir ~/.config/dunst
mkdir ~/.config/picom
mkdir ~/.config/scripts

rm ~/.zshrc

ln -s ~/.flake/setup/.zshrc ~/.zshrc

ln -s ~/.flake/setup/scripts/lightdm.sh ~/.config/scripts/lightdm.sh
ln -s ~/.flake/setup/scripts/polybar.sh ~/.config/scripts/polybar.sh
ln -s ~/.flake/setup/scripts/kill.sh ~/.config/scripts/kill.sh
ln -s ~/.flake/setup/configs/starship.toml ~/.config/starship.toml
ln -s ~/.flake/setup/configs/xmonad.hs ~/.config/xmonad/xmonad.hs
ln -s ~/.flake/setup/configs/dunstrc ~/.config/dunst/dunstrc
ln -s ~/.flake/setup/configs/picom.conf ~/.config/picom/picom.conf
ln -s ~/.flake/setup/configs/polybar-left.ini ~/.config/polybar/polybar-left.ini
ln -s ~/.flake/setup/configs/polybar-right.ini ~/.config/polybar/polybar-right.ini
ln -s ~/.flake/setup/configs/doom.d/doom-rose-pine-moon-theme.el ~/.doom.d/themes/doom-rose-pine-moon-theme.el

echo -e "$COK - Done, Moving to next step..."

echo -e "$CNT - Getting rofi configs..."

git clone https://github.com/allusive-dev/Rofi ~/.config/rofi

rm -rf ~/.config/rofi/.git

echo -e "$COK - Done! Moving On..."

echo -e "$CNT - Installing Jerry"

mkdir /home/allusive/bin

curl -sL github.com/justchokingaround/jerry/raw/main/jerry.sh -o /home/allusive/bin/jerry
chmod +x /home/allusive/bin/jerry

echo -e "$COK - Done! Moving On..."

echo -e "$CNT - Installing Doom Emacs, This will take a while."

git clone https://github.com/hlissner/doom-emacs ~/.emacs.d

~/.emacs.d/bin/doom install

echo -e "$COK - Doom Emacs is installed!"

echo -e "$CNT - Symlinking Doom configs..."

rm ~/.doom.d/*

ln -s ~/.flake/setup/configs/doom.d/config.el ~/.doom.d/config.el
ln -s ~/.flake/setup/configs/doom.d/custom.el ~/.doom.d/custom.el
ln -s ~/.flake/setup/configs/doom.d/init.el ~/.doom.d/init.el
ln -s ~/.flake/setup/configs/doom.d/packages.el ~/.doom.d/packages.el

cp ~/.flake/setup/configs/doom.d/splash.png ~/.doom.d/splash.png

echo -e "$COK - Configs linked!"
